# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

n1 = Player.create(firstname: "Quincy", lastname: "Acy")
n2 = Player.create(firstname: "Steven", lastname: "Adams")
n3 = Player.create(firstname: "Jeff", lastname: "Adrien")
n4 = Player.create(firstname: "Arron", lastname: "Afflalo")
n5 = Player.create(firstname: "Cole", lastname: "Aldrich")
n6 = Player.create(firstname: "LaMarcus", lastname: "Aldridge")
n7 = Player.create(firstname: "Lavoy", lastname: "Allen")
n8 = Player.create(firstname: "Ray", lastname: "Allen")
n9 = Player.create(firstname: "Tony", lastname: "Allen")
n10 = Player.create(firstname: "Al-Farouq", lastname: "Aminu")
n11 = Player.create(firstname: "Lou", lastname: "Amundson")
n12 = Player.create(firstname: "Chris", lastname: "Andersen")
n13 = Player.create(firstname: "Alan", lastname: "Anderson")
n14 = Player.create(firstname: "James", lastname: "Anderson")
n15 = Player.create(firstname: "Ryan", lastname: "Anderson")
n16 = Player.create(firstname: "Giannis", lastname: "Antetokounmpo")
n17 = Player.create(firstname: "Carmelo", lastname: "Anthony").build_social_link(
  twitter: "https://twitter.com/carmeloanthony", 
  youtube: "http://www.youtube.com/ThisIsMeloTV", 
  facebook: "https://www.facebook.com/CarmeloAnthony", 
  tumblr: "http://carmelo-anthony.tumblr.com/", 
  instagram: "http://instagram.com/carmeloanthony", 
  pinterest: "https://www.pinterest.com/carmeloanthony/", 
  googleplus: "https://plus.google.com/+carmeloanthony/posts", 
  weibo: "http://www.weibo.com/carmeloanthony", 
  website: "http://www.thisismelo.com/").save

n18 = Player.create(firstname: "Joel", lastname: "Anthony")
n19 = Player.create(firstname: "Pero", lastname: "Antic")
n20 = Player.create(firstname: "Trevor", lastname: "Ariza")
n21 = Player.create(firstname: "Darrell", lastname: "Arthur")
n22 = Player.create(firstname: "Omer", lastname: "Asik")
n23 = Player.create(firstname: "D.J.", lastname: "Augustin")
n24 = Player.create(firstname: "Gustavo", lastname: "Ayon")
n25 = Player.create(firstname: "Jeff", lastname: "Ayres")
n26 = Player.create(firstname: "Jose Juan", lastname: "Barea")
n27 = Player.create(firstname: "Andrea", lastname: "Bargnani")
n28 = Player.create(firstname: "Harrison", lastname: "Barnes")
n29 = Player.create(firstname: "Matt", lastname: "Barnes")
n30 = Player.create(firstname: "Will", lastname: "Barton")
n31 = Player.create(firstname: "Brandon", lastname: "Bass")
n32 = Player.create(firstname: "Shane", lastname: "Battier")
n33 = Player.create(firstname: "Nicolas", lastname: "Batum")
n34 = Player.create(firstname: "Jerryd", lastname: "Bayless")
n35 = Player.create(firstname: "Aron", lastname: "Baynes")
n36 = Player.create(firstname: "Kent", lastname: "Bazemore")
n37 = Player.create(firstname: "Bradley", lastname: "Beal")
n38 = Player.create(firstname: "Michael", lastname: "Beasley")
n39 = Player.create(firstname: "Marco", lastname: "Belinelli")
n40 = Player.create(firstname: "Anthony", lastname: "Bennett")
n41 = Player.create(firstname: "Dairis", lastname: "Bertans")
n42 = Player.create(firstname: "Patrick", lastname: "Beverley")
n43 = Player.create(firstname: "Andris", lastname: "Biedrins")
n44 = Player.create(firstname: "Chauncey", lastname: "Billups")
n45 = Player.create(firstname: "James", lastname: "Birsen")
n46 = Player.create(firstname: "Bismack", lastname: "Biyombo")
n47 = Player.create(firstname: "Nemanja", lastname: "Bjelica")
n48 = Player.create(firstname: "DeJuan", lastname: "Blair")
n49 = Player.create(firstname: "Steve", lastname: "Blake")
n50 = Player.create(firstname: "Andray", lastname: "Blatche")
n51 = Player.create(firstname: "Eric", lastname: "Bledsoe")
n52 = Player.create(firstname: "Keith", lastname: "Bogans")
n53 = Player.create(firstname: "Bojan", lastname: "Bogdanovic")
n54 = Player.create(firstname: "Andrew", lastname: "Bogut")
n55 = Player.create(firstname: "Matt", lastname: "Bonner")
n56 = Player.create(firstname: "Trevor", lastname: "Booker")
n57 = Player.create(firstname: "Carlos", lastname: "Boozer")
n58 = Player.create(firstname: "Chris", lastname: "Bosh")
n59 = Player.create(firstname: "Avery", lastname: "Bradley")
n60 = Player.create(firstname: "Elton", lastname: "Brand")
n61 = Player.create(firstname: "Corey", lastname: "Brewer")
n62 = Player.create(firstname: "Ronnie", lastname: "Brewer")
n63 = Player.create(firstname: "Aaron", lastname: "Brooks")
n64 = Player.create(firstname: "MarShon", lastname: "Brooks")
n65 = Player.create(firstname: "Kwame", lastname: "Brown")
n66 = Player.create(firstname: "Sherwood", lastname: "Brown")
n67 = Player.create(firstname: "Kobe", lastname: "Bryant")
n68 = Player.create(firstname: "Chase", lastname: "Budinger")
n69 = Player.create(firstname: "Reggie", lastname: "Bullock")
n70 = Player.create(firstname: "Trey", lastname: "Burke")
n71 = Player.create(firstname: "Alec", lastname: "Burks")
n72 = Player.create(firstname: "Caron", lastname: "Butler")
n73 = Player.create(firstname: "Jimmy", lastname: "Butler")
n74 = Player.create(firstname: "Rasual", lastname: "Butler")
n75 = Player.create(firstname: "Dwight", lastname: "Buycks")
n76 = Player.create(firstname: "Andrew", lastname: "Bynum")
n77 = Player.create(firstname: "Will", lastname: "Bynum")
n78 = Player.create(firstname: "Nick", lastname: "Calathes")
n79 = Player.create(firstname: "Jose", lastname: "Calderon")
n80 = Player.create(firstname: "Kentavious", lastname: "Caldwell-Pope")
n81 = Player.create(firstname: "Isaiah", lastname: "Canaan")
n82 = Player.create(firstname: "Jackie", lastname: "Carmichael")
n83 = Player.create(firstname: "DeMarre", lastname: "Carroll")
n84 = Player.create(firstname: "Vince", lastname: "Carter")
n85 = Player.create(firstname: "Michael", lastname: "Carter-Williams")
n86 = Player.create(firstname: "Omri", lastname: "Casspi")
n87 = Player.create(firstname: "Mario", lastname: "Chalmers")
n88 = Player.create(firstname: "Tyson", lastname: "Chandler")
n89 = Player.create(firstname: "Wilson", lastname: "Chandler")
n90 = Player.create(firstname: "Josh", lastname: "Childress")
n91 = Player.create(firstname: "Dionte", lastname: "Christmas")
n92 = Player.create(firstname: "Alex", lastname: "Chubrevich")
n93 = Player.create(firstname: "Earl", lastname: "Clark")
n94 = Player.create(firstname: "Ian", lastname: "Clark")
n95 = Player.create(firstname: "Victor", lastname: "Claver")
n96 = Player.create(firstname: "Norris", lastname: "Cole")
n97 = Player.create(firstname: "Darren", lastname: "Collison")
n98 = Player.create(firstname: "Nick", lastname: "Collison")
n99 = Player.create(firstname: "Mike", lastname: "Conley")
n100 = Player.create(firstname: "Chris", lastname: "Copeland")
n101 = Player.create(firstname: "DeMarcus", lastname: "Cousins")
n102 = Player.create(firstname: "Robert", lastname: "Covington")
n103 = Player.create(firstname: "Allen", lastname: "Crabbe")
n104 = Player.create(firstname: "Jamal", lastname: "Crawford")
n105 = Player.create(firstname: "Jordan", lastname: "Crawford")
n106 = Player.create(firstname: "Jae", lastname: "Crowder")
n107 = Player.create(firstname: "David", lastname: "Cubillan")
n108 = Player.create(firstname: "Dante", lastname: "Cunningham")
n109 = Player.create(firstname: "Jared", lastname: "Cunningham")
n110 = Player.create(firstname: "Stephen", lastname: "Curry")
n111 = Player.create(firstname: "Samuel", lastname: "Dalembert")
n112 = Player.create(firstname: "Gigi", lastname: "Datome")
n113 = Player.create(firstname: "Brandon", lastname: "Davies")
n114 = Player.create(firstname: "Anthony", lastname: "Davis")
n115 = Player.create(firstname: "Ed", lastname: "Davis")
n116 = Player.create(firstname: "Glen", lastname: "Davis")
n117 = Player.create(firstname: "Austin", lastname: "Daye")
n118 = Player.create(firstname: "Nando", lastname: "De Colo")
n119 = Player.create(firstname: "DeMar", lastname: "DeRozan")
n120 = Player.create(firstname: "Dewayne", lastname: "Dedmon")
n121 = Player.create(firstname: "Carlos", lastname: "Delfino")
n122 = Player.create(firstname: "Matthew", lastname: "Dellavedova")
n123 = Player.create(firstname: "Luol", lastname: "Deng")
n124 = Player.create(firstname: "Boris", lastname: "Diaw")
n125 = Player.create(firstname: "Gorgui", lastname: "Dieng")
n126 = Player.create(firstname: "Toney", lastname: "Douglas")
n127 = Player.create(firstname: "Goran", lastname: "Dragic")
n128 = Player.create(firstname: "Andre", lastname: "Drummond")
n129 = Player.create(firstname: "Jared", lastname: "Dudley")
n130 = Player.create(firstname: "Tim", lastname: "Duncan")
n131 = Player.create(firstname: "Mike", lastname: "Dunleavy")
n132 = Player.create(firstname: "Kevin", lastname: "Durant")
n133 = Player.create(firstname: "Wayne", lastname: "Ellington")
n134 = Player.create(firstname: "Monta", lastname: "Ellis")
n135 = Player.create(firstname: "Baris", lastname: "Ermis")
n136 = Player.create(firstname: "Jeremy", lastname: "Evans")
n137 = Player.create(firstname: "Reggie", lastname: "Evans")
n138 = Player.create(firstname: "Tyreke", lastname: "Evans")
n139 = Player.create(firstname: "Festus", lastname: "Ezeli")
n140 = Player.create(firstname: "Kenneth", lastname: "Faried")
n141 = Player.create(firstname: "Jordan", lastname: "Farmar")
n142 = Player.create(firstname: "Vitor", lastname: "Faverani")
n143 = Player.create(firstname: "Derrick", lastname: "Favors")
n144 = Player.create(firstname: "Carrick", lastname: "Felix")
n145 = Player.create(firstname: "Raymond", lastname: "Felton")
n146 = Player.create(firstname: "Landry", lastname: "Fields")
n147 = Player.create(firstname: "Derek", lastname: "Fisher")
n148 = Player.create(firstname: "Evan", lastname: "Fournier")
n149 = Player.create(firstname: "Randy", lastname: "Foye")
n150 = Player.create(firstname: "Jamaal", lastname: "Franklin")
n151 = Player.create(firstname: "Jimmer", lastname: "Fredette")
n152 = Player.create(firstname: "Joel", lastname: "Freeland")
n153 = Player.create(firstname: "Vitaly", lastname: "Fridzon")
n154 = Player.create(firstname: "Channing", lastname: "Frye")
n155 = Player.create(firstname: "German", lastname: "Gabriel")
n156 = Player.create(firstname: "Danilo", lastname: "Gallinari")
n157 = Player.create(firstname: "Francisco", lastname: "Garcia")
n158 = Player.create(firstname: "Kevin", lastname: "Garnett")
n159 = Player.create(firstname: "Diante", lastname: "Garrett")
n160 = Player.create(firstname: "Marc", lastname: "Gasol")
n161 = Player.create(firstname: "Pau", lastname: "Gasol")
n162 = Player.create(firstname: "Rudy", lastname: "Gay")
n163 = Player.create(firstname: "Alonzo", lastname: "Gee")
n164 = Player.create(firstname: "Paul", lastname: "George")
n165 = Player.create(firstname: "Taj", lastname: "Gibson")
n166 = Player.create(firstname: "Manu", lastname: "Ginobili")
n167 = Player.create(firstname: "Rudy", lastname: "Gobert")
n168 = Player.create(firstname: "Ryan", lastname: "Gomes")
n169 = Player.create(firstname: "Archie", lastname: "Goodwin")
n170 = Player.create(firstname: "Ben", lastname: "Gordon")
n171 = Player.create(firstname: "Eric", lastname: "Gordon")
n172 = Player.create(firstname: "Marcin", lastname: "Gortat")
n173 = Player.create(firstname: "Danny", lastname: "Granger")
n174 = Player.create(firstname: "Aaron", lastname: "Gray")
n175 = Player.create(firstname: "Danny", lastname: "Green")
n176 = Player.create(firstname: "Draymond", lastname: "Green")
n177 = Player.create(firstname: "Gerald", lastname: "Green")
n178 = Player.create(firstname: "Jeff", lastname: "Green")
n179 = Player.create(firstname: "Willie", lastname: "Green")
n180 = Player.create(firstname: "Blake", lastname: "Griffin")
n181 = Player.create(firstname: "Roger", lastname: "Grimau")
n182 = Player.create(firstname: "Alexandr", lastname: "Gudumak")
n183 = Player.create(firstname: "Jordan", lastname: "Hamilton")
n184 = Player.create(firstname: "Tyler", lastname: "Hansbrough")
n185 = Player.create(firstname: "Timothy", lastname: "Hardaway Jr.")
n186 = Player.create(firstname: "James", lastname: "Harden")
n187 = Player.create(firstname: "Maurice", lastname: "Harkless")
n188 = Player.create(firstname: "Josh", lastname: "Harrellson")
n189 = Player.create(firstname: "Al", lastname: "Harrington")
n190 = Player.create(firstname: "Devin", lastname: "Harris")
n191 = Player.create(firstname: "Elias", lastname: "Harris")
n192 = Player.create(firstname: "Michael", lastname: "Harris")
n193 = Player.create(firstname: "Tobias", lastname: "Harris")
n194 = Player.create(firstname: "Udonis", lastname: "Haslem")
n195 = Player.create(firstname: "Spencer", lastname: "Hawes")
n196 = Player.create(firstname: "Charles", lastname: "Hayes")
n197 = Player.create(firstname: "Gordon", lastname: "Hayward")
n198 = Player.create(firstname: "Brendan", lastname: "Haywood")
n199 = Player.create(firstname: "Gerald", lastname: "Henderson")
n200 = Player.create(firstname: "Xavier", lastname: "Henry")
n201 = Player.create(firstname: "John", lastname: "Henson")
n202 = Player.create(firstname: "Axel", lastname: "Hervelle")
n203 = Player.create(firstname: "Roy", lastname: "Hibbert")
n204 = Player.create(firstname: "JJ", lastname: "Hickson")
n205 = Player.create(firstname: "George", lastname: "Hill")
n206 = Player.create(firstname: "Jordan", lastname: "Hill")
n207 = Player.create(firstname: "Solomon", lastname: "Hill")
n208 = Player.create(firstname: "Kyle", lastname: "Hines")
n209 = Player.create(firstname: "Kirk", lastname: "Hinrich")
n210 = Player.create(firstname: "Jrue", lastname: "Holiday")
n211 = Player.create(firstname: "Ryan", lastname: "Hollins")
n212 = Player.create(firstname: "Al", lastname: "Horford")
n213 = Player.create(firstname: "Dwight", lastname: "Howard")
n214 = Player.create(firstname: "Robbie", lastname: "Hummel")
n215 = Player.create(firstname: "Kris", lastname: "Humphries")
n216 = Player.create(firstname: "Serge", lastname: "Ibaka")
n217 = Player.create(firstname: "Andre", lastname: "Iguodala")
n218 = Player.create(firstname: "Ersan", lastname: "Ilyasova")
n219 = Player.create(firstname: "Kyrie", lastname: "Irving")
n220 = Player.create(firstname: "Jarrett", lastname: "Jack")
n221 = Player.create(firstname: "Aaron", lastname: "Jackson")
n222 = Player.create(firstname: "Reggie", lastname: "Jackson")
n223 = Player.create(firstname: "Bernard", lastname: "James")
n224 = Player.create(firstname: "LeBron", lastname: "James")
n225 = Player.create(firstname: "Mike", lastname: "James")
n226 = Player.create(firstname: "Antawn", lastname: "Jamison")
n227 = Player.create(firstname: "Al", lastname: "Jefferson")
n228 = Player.create(firstname: "Richard", lastname: "Jefferson")
n229 = Player.create(firstname: "John", lastname: "Jenkins")
n230 = Player.create(firstname: "Brandon", lastname: "Jennings")
n231 = Player.create(firstname: "Jonas", lastname: "Jerebko")
n232 = Player.create(firstname: "Amir", lastname: "Johnson")
n233 = Player.create(firstname: "Joe", lastname: "Johnson")
n234 = Player.create(firstname: "Orlando", lastname: "Johnson")
n235 = Player.create(firstname: "Wesley", lastname: "Johnson")
n236 = Player.create(firstname: "James", lastname: "Jones")
n237 = Player.create(firstname: "Perry", lastname: "Jones")
n238 = Player.create(firstname: "Solomon", lastname: "Jones")
n239 = Player.create(firstname: "Terrence", lastname: "Jones")
n240 = Player.create(firstname: "DeAndre", lastname: "Jordan")
n241 = Player.create(firstname: "Cory", lastname: "Joseph")
n242 = Player.create(firstname: "Chris", lastname: "Kaman")
n243 = Player.create(firstname: "Enes", lastname: "Kanter")
n244 = Player.create(firstname: "Ilkan", lastname: "Karaman")
n245 = Player.create(firstname: "Sergey", lastname: "Karasev")
n246 = Player.create(firstname: "Sasha", lastname: "Kaun")
n247 = Player.create(firstname: "Antanas", lastname: "Kavaliauskas")
n248 = Player.create(firstname: "Ryan", lastname: "Kelly")
n249 = Player.create(firstname: "Victor", lastname: "Khryapa")
n250 = Player.create(firstname: "Michael", lastname: "Kidd-Gilchrist")
n251 = Player.create(firstname: "Andrei", lastname: "Kirilenko")
n252 = Player.create(firstname: "Linas", lastname: "Kleiza")
n253 = Player.create(firstname: "Brandon", lastname: "Knight")
n254 = Player.create(firstname: "Uri", lastname: "Kokia")
n255 = Player.create(firstname: "Kyle", lastname: "Korver")
n256 = Player.create(firstname: "Kosta", lastname: "Koufos")
n257 = Player.create(firstname: "Ido", lastname: "Kozikaro")
n258 = Player.create(firstname: "Viacheslav", lastname: "Kravtsov")
n259 = Player.create(firstname: "Nenad", lastname: "Krstic")
n260 = Player.create(firstname: "Ognjen", lastname: "Kuzmic")
n261 = Player.create(firstname: "Doron", lastname: "Lamb")
n262 = Player.create(firstname: "Jeremy", lastname: "Lamb")
n263 = Player.create(firstname: "Carl", lastname: "Landry")
n264 = Player.create(firstname: "Shane", lastname: "Larkin")
n265 = Player.create(firstname: "Ty", lastname: "Lawson")
n266 = Player.create(firstname: "Ricky", lastname: "Ledo")
n267 = Player.create(firstname: "Courtney", lastname: "Lee")
n268 = Player.create(firstname: "David", lastname: "Lee")
n269 = Player.create(firstname: "Alex", lastname: "Len")
n270 = Player.create(firstname: "Kawhi", lastname: "Leonard")
n271 = Player.create(firstname: "Meyers", lastname: "Leonard")
n272 = Player.create(firstname: "Jon", lastname: "Leuer")
n273 = Player.create(firstname: "Rashard", lastname: "Lewis")
n274 = Player.create(firstname: "Damian", lastname: "Lillard")
n275 = Player.create(firstname: "Jeremy", lastname: "Lin")
n276 = Player.create(firstname: "Shaun", lastname: "Livingston")
n277 = Player.create(firstname: "Brook", lastname: "Lopez")
n278 = Player.create(firstname: "Raul", lastname: "Lopez")
n279 = Player.create(firstname: "Robin", lastname: "Lopez")
n280 = Player.create(firstname: "Kevin", lastname: "Love")
n281 = Player.create(firstname: "Kyle", lastname: "Lowry")
n282 = Player.create(firstname: "John", lastname: "Lucas III")
n283 = Player.create(firstname: "Nikola", lastname: "Lucic")
n284 = Player.create(firstname: "Shelvin", lastname: "Mack")
n285 = Player.create(firstname: "Ian", lastname: "Mahinmi")
n286 = Player.create(firstname: "Melih", lastname: "Mahmutoglu")
n287 = Player.create(firstname: "Shawn", lastname: "Marion")
n288 = Player.create(firstname: "Cartier", lastname: "Martin")
n289 = Player.create(firstname: "Kenyon", lastname: "Martin")
n290 = Player.create(firstname: "Kevin", lastname: "Martin")
n291 = Player.create(firstname: "Roger", lastname: "Mason Jr.")
n292 = Player.create(firstname: "Wesley", lastname: "Matthews")
n293 = Player.create(firstname: "Jason", lastname: "Maxiell")
n294 = Player.create(firstname: "Eric", lastname: "Maynor")
n295 = Player.create(firstname: "O.J.", lastname: "Mayo")
n296 = Player.create(firstname: "Luc", lastname: "Mbah a Moute")
n297 = Player.create(firstname: "Bo", lastname: "McCalebb")
n298 = Player.create(firstname: "Ray", lastname: "McCallum")
n299 = Player.create(firstname: "CJ", lastname: "McCollum")
n300 = Player.create(firstname: "JaVale", lastname: "McGee")
n301 = Player.create(firstname: "Ben", lastname: "McLemore")
n302 = Player.create(firstname: "Josh", lastname: "McRoberts")
n303 = Player.create(firstname: "Jodie", lastname: "Meeks")
n304 = Player.create(firstname: "Gal", lastname: "Mekel")
n305 = Player.create(firstname: "Borja", lastname: "Mendia")
n306 = Player.create(firstname: "Vladimir", lastname: "Micov")
n307 = Player.create(firstname: "Khris", lastname: "Middleton")
n308 = Player.create(firstname: "CJ", lastname: "Miles")
n309 = Player.create(firstname: "Andre", lastname: "Miller")
n310 = Player.create(firstname: "Darius", lastname: "Miller")
n311 = Player.create(firstname: "Mike", lastname: "Miller")
n312 = Player.create(firstname: "Quincy", lastname: "Miller")
n313 = Player.create(firstname: "Patty", lastname: "Mills")
n314 = Player.create(firstname: "Paul", lastname: "Millsap")
n315 = Player.create(firstname: "Tony", lastname: "Mitchell")
n316 = Player.create(firstname: "Nazr", lastname: "Mohammed")
n317 = Player.create(firstname: "Greg", lastname: "Monroe")
n318 = Player.create(firstname: "E'Twaun", lastname: "Moore")
n319 = Player.create(firstname: "Darius", lastname: "Morris")
n320 = Player.create(firstname: "Marcus", lastname: "Morris")
n321 = Player.create(firstname: "Markieff", lastname: "Morris")
n322 = Player.create(firstname: "Anthony", lastname: "Morrow")
n323 = Player.create(firstname: "Donatas", lastname: "Motiejunas")
n324 = Player.create(firstname: "Arnett", lastname: "Moultrie")
n325 = Player.create(firstname: "Timofey", lastname: "Mozgov")
n326 = Player.create(firstname: "Shabazz", lastname: "Muhammad")
n327 = Player.create(firstname: "Byron", lastname: "Mullens")
n328 = Player.create(firstname: "Alex", lastname: "Mumbru")
n329 = Player.create(firstname: "Erik", lastname: "Murphy")
n330 = Player.create(firstname: "Toure", lastname: "Murry")
n331 = Player.create(firstname: "", lastname: "Nene")
n332 = Player.create(firstname: "Steve", lastname: "Nash")
n333 = Player.create(firstname: "Hamady", lastname: "Ndiaye")
n334 = Player.create(firstname: "Gary", lastname: "Neal")
n335 = Player.create(firstname: "Nemanja", lastname: "Nedovic")
n336 = Player.create(firstname: "Jameer", lastname: "Nelson")
n337 = Player.create(firstname: "Andrew", lastname: "Nicholson")
n338 = Player.create(firstname: "Joakim", lastname: "Noah")
n339 = Player.create(firstname: "Nerlens", lastname: "Noel")
n340 = Player.create(firstname: "Steve", lastname: "Novak")
n341 = Player.create(firstname: "Dirk", lastname: "Nowitzki")
n342 = Player.create(firstname: "Jermaine", lastname: "O'Neal")
n343 = Player.create(firstname: "Kyle", lastname: "O'Quinn")
n344 = Player.create(firstname: "Greg", lastname: "Oden")
n345 = Player.create(firstname: "Ike", lastname: "Ofoegbu")
n346 = Player.create(firstname: "Emeka", lastname: "Okafor")
n347 = Player.create(firstname: "Victor", lastname: "Oladipo")
n348 = Player.create(firstname: "Ayberk", lastname: "Olmaz")
n349 = Player.create(firstname: "Kelly", lastname: "Olynyk")
n350 = Player.create(firstname: "Omer", lastname: "Onan")
n351 = Player.create(firstname: "Daniel", lastname: "Orton")
n352 = Player.create(firstname: "Travis", lastname: "Outlaw")
n353 = Player.create(firstname: "Zaza", lastname: "Pachulia")
n354 = Player.create(firstname: "Jannero", lastname: "Pargo")
n355 = Player.create(firstname: "Jeremy", lastname: "Pargo")
n356 = Player.create(firstname: "Tony", lastname: "Parker")
n357 = Player.create(firstname: "Chandler", lastname: "Parsons")
n358 = Player.create(firstname: "Patrick", lastname: "Patterson")
n359 = Player.create(firstname: "Chris", lastname: "Paul")
n360 = Player.create(firstname: "Nikola", lastname: "Pekovic")
n361 = Player.create(firstname: "Kendrick", lastname: "Perkins")
n362 = Player.create(firstname: "Paul", lastname: "Pierce")
n363 = Player.create(firstname: "Fran", lastname: "Pilepic")
n364 = Player.create(firstname: "Mason", lastname: "Plumlee")
n365 = Player.create(firstname: "Miles", lastname: "Plumlee")
n366 = Player.create(firstname: "Quincy", lastname: "Pondexter")
n367 = Player.create(firstname: "Otto", lastname: "Porter")
n368 = Player.create(firstname: "Emir", lastname: "Preldzic")
n369 = Player.create(firstname: "Phil", lastname: "Pressey")
n370 = Player.create(firstname: "A.J.", lastname: "Price")
n371 = Player.create(firstname: "Ronnie", lastname: "Price")
n372 = Player.create(firstname: "Pablo", lastname: "Prigioni")
n373 = Player.create(firstname: "Tayshaun", lastname: "Prince")
n374 = Player.create(firstname: "Miroslav", lastname: "Raduljica")
n375 = Player.create(firstname: "Brian", lastname: "Randle")
n376 = Player.create(firstname: "Anthony", lastname: "Randolph")
n377 = Player.create(firstname: "Zach", lastname: "Randolph")
n378 = Player.create(firstname: "JJ", lastname: "Redick")
n379 = Player.create(firstname: "Ben", lastname: "Reis")
n380 = Player.create(firstname: "Glen", lastname: "Rice Jr.")
n381 = Player.create(firstname: "Jason", lastname: "Richardson")
n382 = Player.create(firstname: "Luke", lastname: "Ridnour")
n383 = Player.create(firstname: "Austin", lastname: "Rivers")
n384 = Player.create(firstname: "Andre", lastname: "Roberson")
n385 = Player.create(firstname: "Brian", lastname: "Roberts")
n386 = Player.create(firstname: "Nate", lastname: "Robinson")
n387 = Player.create(firstname: "Thomas", lastname: "Robinson")
n388 = Player.create(firstname: "Rajon", lastname: "Rondo")
n389 = Player.create(firstname: "Derrick", lastname: "Rose")
n390 = Player.create(firstname: "Terrence", lastname: "Ross")
n391 = Player.create(firstname: "Moran", lastname: "Roth")
n392 = Player.create(firstname: "Ricky", lastname: "Rubio")
n393 = Player.create(firstname: "Brandon", lastname: "Rush")
n394 = Player.create(firstname: "Robert", lastname: "Sacre")
n395 = Player.create(firstname: "John", lastname: "Salmons")
n396 = Player.create(firstname: "Mamadou", lastname: "Samb")
n397 = Player.create(firstname: "Sergio", lastname: "Sanchez")
n398 = Player.create(firstname: "Larry", lastname: "Sanders")
n399 = Player.create(firstname: "Oguz", lastname: "Savas")
n400 = Player.create(firstname: "Dennis", lastname: "Schroeder")
n401 = Player.create(firstname: "Luis", lastname: "Scola")
n402 = Player.create(firstname: "Mike", lastname: "Scott")
n403 = Player.create(firstname: "Thabo", lastname: "Sefolosha")
n404 = Player.create(firstname: "Kevin", lastname: "Seraphin")
n405 = Player.create(firstname: "Ramon", lastname: "Sessions")
n406 = Player.create(firstname: "Tornike", lastname: "Shengelia")
n407 = Player.create(firstname: "Grigori", lastname: "Shukhovtsov")
n408 = Player.create(firstname: "Iman", lastname: "Shumpert")
n409 = Player.create(firstname: "Alexey", lastname: "Shved")
n410 = Player.create(firstname: "Henry", lastname: "Sims")
n411 = Player.create(firstname: "Kyle", lastname: "Singler")
n412 = Player.create(firstname: "Chris", lastname: "Singleton")
n413 = Player.create(firstname: "Kenan", lastname: "Sipahi")
n414 = Player.create(firstname: "Peyton", lastname: "Siva")
n415 = Player.create(firstname: "Donald", lastname: "Sloan")
n416 = Player.create(firstname: "Chris", lastname: "Smith")
n417 = Player.create(firstname: "Donta", lastname: "Smith")
n418 = Player.create(firstname: "Greg", lastname: "Smith")
n419 = Player.create(firstname: "Ish", lastname: "Smith")
n420 = Player.create(firstname: "J.R.", lastname: "Smith")
n421 = Player.create(firstname: "Jason", lastname: "Smith")
n422 = Player.create(firstname: "Josh", lastname: "Smith")
n423 = Player.create(firstname: "Tony", lastname: "Snell")
n424 = Player.create(firstname: "James", lastname: "Southerland")
n425 = Player.create(firstname: "Marreese", lastname: "Speights")
n426 = Player.create(firstname: "Tiago", lastname: "Splitter")
n427 = Player.create(firstname: "Lance", lastname: "Stephenson")
n428 = Player.create(firstname: "Greg", lastname: "Stiemsma")
n429 = Player.create(firstname: "Julyan", lastname: "Stone")
n430 = Player.create(firstname: "Amar'e", lastname: "Stoudemire")
n431 = Player.create(firstname: "Rodney", lastname: "Stuckey")
n432 = Player.create(firstname: "Jared", lastname: "Sullinger")
n433 = Player.create(firstname: "Jeff", lastname: "Taylor")
n434 = Player.create(firstname: "Tyshawn", lastname: "Taylor")
n435 = Player.create(firstname: "Jeff", lastname: "Teague")
n436 = Player.create(firstname: "Marquis", lastname: "Teague")
n437 = Player.create(firstname: "Mirza", lastname: "Teletovic")
n438 = Player.create(firstname: "Garrett", lastname: "Temple")
n439 = Player.create(firstname: "Milos", lastname: "Teodosic")
n440 = Player.create(firstname: "Jason", lastname: "Terry")
n441 = Player.create(firstname: "Hasheem", lastname: "Thabeet")
n442 = Player.create(firstname: "Isaiah", lastname: "Thomas")
n443 = Player.create(firstname: "Hollis", lastname: "Thompson")
n444 = Player.create(firstname: "Jason", lastname: "Thompson")
n445 = Player.create(firstname: "Klay", lastname: "Thompson")
n446 = Player.create(firstname: "Tristan", lastname: "Thompson")
n447 = Player.create(firstname: "Marcus", lastname: "Thornton")
n448 = Player.create(firstname: "Anthony", lastname: "Tolliver")
n449 = Player.create(firstname: "PJ", lastname: "Tucker")
n450 = Player.create(firstname: "Ronny", lastname: "Turiaf")
n451 = Player.create(firstname: "Hedo", lastname: "Turkoglu")
n452 = Player.create(firstname: "Izzet", lastname: "Turkyilmaz")
n453 = Player.create(firstname: "Evan", lastname: "Turner")
n454 = Player.create(firstname: "Ekpe", lastname: "Udoh")
n455 = Player.create(firstname: "Beno", lastname: "Udrih")
n456 = Player.create(firstname: "Berk", lastname: "Ugurlu")
n457 = Player.create(firstname: "Jonas", lastname: "Valanciunas")
n458 = Player.create(firstname: "Anderson", lastname: "Varejao")
n459 = Player.create(firstname: "Greivis", lastname: "Vasquez")
n460 = Player.create(firstname: "Jan", lastname: "Vesely")
n461 = Player.create(firstname: "Gasper", lastname: "Vidmar")
n462 = Player.create(firstname: "Charlie", lastname: "Villanueva")
n463 = Player.create(firstname: "Eugeny", lastname: "Voronov")
n464 = Player.create(firstname: "Andrey", lastname: "Vorontsevich")
n465 = Player.create(firstname: "Zoran", lastname: "Vrkic")
n466 = Player.create(firstname: "Nikola", lastname: "Vucevic")
n467 = Player.create(firstname: "Dwyane", lastname: "Wade")
n468 = Player.create(firstname: "Dion", lastname: "Waiters")
n469 = Player.create(firstname: "Kemba", lastname: "Walker")
n470 = Player.create(firstname: "John", lastname: "Wall")
n471 = Player.create(firstname: "Gerald", lastname: "Wallace")
n472 = Player.create(firstname: "CJ", lastname: "Watson")
n473 = Player.create(firstname: "Earl", lastname: "Watson")
n474 = Player.create(firstname: "Maalik", lastname: "Wayns")
n475 = Player.create(firstname: "Martell", lastname: "Webster")
n476 = Player.create(firstname: "Sonny", lastname: "Weems")
n477 = Player.create(firstname: "David", lastname: "West")
n478 = Player.create(firstname: "Russell", lastname: "Westbrook")
n479 = Player.create(firstname: "Deron", lastname: "Williams")
n480 = Player.create(firstname: "Derrick", lastname: "Williams")
n481 = Player.create(firstname: "Louis", lastname: "Williams")
n482 = Player.create(firstname: "Marvin", lastname: "Williams")
n483 = Player.create(firstname: "Mo", lastname: "Williams")
n484 = Player.create(firstname: "Shawne", lastname: "Williams")
n485 = Player.create(firstname: "Jeff", lastname: "Withey")
n486 = Player.create(firstname: "Nate", lastname: "Wolters")
n487 = Player.create(firstname: "Metta", lastname: "World Peace")
n488 = Player.create(firstname: "Brandan", lastname: "Wright")
n489 = Player.create(firstname: "Dorell", lastname: "Wright")
n490 = Player.create(firstname: "Tony", lastname: "Wroten")
n491 = Player.create(firstname: "Dagan", lastname: "Yivzuri")
n492 = Player.create(firstname: "Nick", lastname: "Young")
n493 = Player.create(firstname: "Thaddeus", lastname: "Young")
n494 = Player.create(firstname: "Omer", lastname: "Yurtseven")
n495 = Player.create(firstname: "Cody", lastname: "Zeller")
n496 = Player.create(firstname: "Tyler", lastname: "Zeller")
n497 = Player.create(firstname: "Nikos", lastname: "Zisis")
n498 = Player.create(firstname: "Luka", lastname: "Zoric")
n499 = Player.create(firstname: "Aleksey", lastname: "Zozulin")


SocialLink.create(
  player_id: 58, 
  twitter: "https://twitter.com/chrisbosh", 
  youtube: "", 
  facebook: "https://www.facebook.com/OfficialChrisBosh", 
  tumblr: "http://teambosh.tumblr.com/", 
  instagram: "http://instagram.com/chrisbosh", 
  pinterest: "", 
  googleplus: "", 
  weibo: "", 
  website: "http://www.chrisbosh.com/")
SocialLink.create(
  player_id: 67, 
  twitter: "https://twitter.com/kobebryant", 
  youtube: "", 
  facebook: "https://www.facebook.com/Kobe", 
  tumblr: "", 
  instagram: "http://instagram.com/kobebryant", 
  pinterest: "", 
  googleplus: "", 
  weibo: "", 
  website: "http://kobebryant.com/")
SocialLink.create(
  player_id: 88, 
  twitter: "https://twitter.com/tysonchandler", 
  youtube: "", 
  facebook: "https://www.facebook.com/tysonchandler", 
  tumblr: "", 
  instagram: "", 
  pinterest: "", 
  googleplus: "https://plus.google.com/114052512597012721199/posts", 
  weibo: "", 
  website: "http://tysonchandler.com/")
SocialLink.create(
  player_id: 224, 
  twitter: "https://twitter.com/kingjames", 
  youtube: "", 
  facebook: "https://www.facebook.com/LeBron", 
  tumblr: "", 
  instagram: "", 
  pinterest: "", 
  googleplus: "", 
  weibo: "", 
  website: "http://www.lebronjames.com/")
SocialLink.create(
  player_id: 275, 
  twitter: "https://twitter.com/JLin7", 
  youtube: "http://www.youtube.com/thejlin7", 
  facebook: "https://www.facebook.com/jeremylin7", 
  tumblr: "",
  instagram: "", 
  pinterest: "", 
  googleplus: "", 
  weibo: "http://www.weibo.com/jlin7", 
  website: "http://www.jlin7.com/")
SocialLink.create(
  player_id: 389, 
  twitter: "https://twitter.com/drose", 
  youtube: "http://www.youtube.com/derrickrose", 
  facebook: "https://www.facebook.com/derrickrose", 
  tumblr: "", 
  instagram: "", 
  pinterest: "", 
  googleplus: "", 
  weibo: "http://t.qq.com/DerrickRose", 
  website: "http://www.drosehoops.com/")
